### ISSUE TITLE
Implement Logout Button

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms-ui#56] opened 2020-08-13 15:47 UTC
## Objective
Pre-Req: User has already logged into the portal.
User has the ability to log out from the portal.

## Acceptance Criteria

- [ ] User has the ability to logout from the portal.
- [ ] When the user clicks "logout" they are taken to the data explorer page with the login button in the top right side.

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/0e9facaf-b12c-4e70-a0c2-735d01452a42)

## Zeplin Link
Styling for Logout Button is covered in this ticket: https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/overture-stack/roadmap/69

**Comment by b-f-chan** [comment] 2021-03-02 17:40
Tested on staging:

- If logged in and viewing the Data Explorer page, logout redirects them to the login page (where you pick your provider), instead of keeping them in Data Explorer (except logged out), as indicated in the original test criteria.  I think this makes sense because the user may still be wanting to view the data and not necessarily log back in.  Small detail, but we can confirm with @kcullion the intended/original behaviour.

- If logged in and viewing the User Profile page however, logout does redirect them to the login page.  In this case this behaviour makes sense, because they should not be able to see any sensitive profile info (e.g. API token, contact e-mail) unless logged in, so it is better to redirect them to the login page.

**Comment by b-f-chan** [comment] 2021-03-02 18:34
Confirmed with @kcullion, logging out from the data explorer page should keep them there.  As I mentioned, users may likely want to keep exploring the data and not necessarily log back in.

If they logout from the profile page, @kcullion states normally we would take them to a homepage or landing page (e.g. like in ARGO).  But since DMS does not have a home or landing page, to be consistent, we should bring them back to the data explorer as well (whenever they log out from anywhere).  Effectively we're treating the data explorer page as a landing page here.

**Comment by b-f-chan** [comment] 2021-03-09 17:49
Re-tested on staging, logout behaviour fixed - No matter where I logout from (Login page, Data Explorer, Profile page), it always redirects the user to the Data Explorer

Closing

**Closed by b-f-chan** 2021-03-09 17:49 UTC
Labels: 0.5.0, 0.6.0, SP:1, canarie
