### ISSUE TITLE
Add Manifest Download Option

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms-ui#57] opened 2020-09-03 16:31 UTC
Add the Manifest download option to the Download button in the data explorer results table

The manifest file will be generated and can be downloaded by users to their machine.  Using the manifest file, the user can download all files from the Score client.

Scenario 1: Users can individually select specific files and when they click Download Manifest, the generated manifest will only apply to those files

Scenario 2: Users can simply click Download Manifest without selecting files, and the Manifest file will be generated for ALL files

## Design link
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5f36e1d30eebd7244a058c1d

## Dev tasks

@caravinci to first investigate how the file is generated and streamed to the UI (e.g. what endpoint being used, any setup required, etc) - Can use ARGO manifest download as a starting example (see attached)

** MANIFEST FIELDS **

Use same 11 fields in the current ARGO manifest (cannot attach TSV, please go here and click Download Manifest in the results table: https://platform.icgc-argo.org/repository?filters=%7B%22content%22%3A%5B%5D%2C%22op%22%3A%22and%22%7D)

Note that these fields are required at minimum and cannot be removed: Object ID, Analysis ID, File Type, File Name

**Comment by b-f-chan** [comment] 2021-03-05 17:15
RE: Gokul original comment - This is no longer nice-to-have but mandatory for MVP.

#644 is solved, @caravinci will help investigate how the data is pulled and file generated (must be some endpoint?) - Can look at ARGO manifest download as example - Please post results here, assigning to @caravinci for now

**Comment by caravinci** [comment] 2021-03-06 00:55
For context: [The props passed to Arranger's Table](https://github.com/overture-stack/dms-ui/blob/develop/components/pages/repository/RepoTable.tsx#L213) in Canarie's RepoTable allow the passing an `exporter` function, which inside Arranger defaults to using a helper called saveTSV ([as seen here](https://github.com/overture-stack/arranger/blob/develop/modules/components/src/DataTable/TableToolbar/saveTSV.js), which I'm sharing in hope to assist implementation of the Manifest processing function.)

Currently, passing a different function to `exporter` (along with a different 'exportTSVText' to label the button), may achieve whatever intended result, while replacing/removing the TSV download capabilities.

There's also a boolean props called `allowTSVExport`, which defaults to true. 
Oddly enough, that props hides or shows the button, regardless of whether the exporter function is TSV related or not.
This behaviour doesn't seem intuitive, so I intend on correcting it: i.e. if a custom exporter function is given, this boolean will be ignored, and the button will be shown regardless of it.

Ensuring backwards compatibility, and as a viable enhancement, we can allow for that `exporter` props to also accept an array of objects (each including a processing function, and a dropdown item label), which would enable adding as many options as the component integrators are willing to implement.
I must figure out a functional and usable way to allow indicating the `TSV download` inside that array (for Arranger to use the default function), in case future integrators want to choose its position amongst other options.

---
Does this seem like a reasonable approach to you? @anncatton @joneubank @b-f-chan

**Comment by caravinci** [comment] 2021-03-19 15:01
Follow up from previous comment: 
- We discussed details offline (over slack), and this approach seems to be adequate.
- The requirements in this ticket for Arranger will be addressed in [arranger#658 - multiple download functions](https://github.com/overture-stack/arranger/issues/658) and [arranger#661 - table row selection as download filter](https://github.com/overture-stack/arranger/issues/661)

**Comment by caravinci** [comment] 2021-03-19 20:44
Opening PR for [arranger#658 (multiple download functions)](https://github.com/overture-stack/arranger/issues/658)
This ticket depends on those changes being published.

Pull request: https://github.com/overture-stack/arranger/pull/662

**Comment by caravinci** [comment] 2021-03-23 17:56
Progress update: Feature published on the Arranger/components side, and I've just merged the PR for this ticket into `develop`.
Currently deploying to QA to enable testing.

**Comment by b-f-chan** [comment] 2021-03-24 15:58
**Tested on QA:**

- Manifest button correctly downloads manifest file with correct contents (all rows by default, or specific rows if selected)

**Outstanding fixes/questions:**

- Sorry I forgot to specify the filename formats, can we fix for both TSV and Manifest?
    -TSV: `data-explorer-table-export.<yyyymmdd>.tsv`
    - Manifest (we’ll follow ARGO): `score-manifest.<yyyymmdd>.tsv`

- Need to confirm with @rosibaj if the manifest column header names need to be the actual ES field name (e.g. `analysis_id`).  I noticed this is the case in ARGO.  What we have here is the Arranger display name (e.g. `Analysis ID`).  Not sure if it matters though.

**Comment by b-f-chan** [comment] 2021-03-25 20:38
Filename fixed and tested on QA and staging, working fine

Confirmed the column names in manifest are fine as is

Closing

**Closed by b-f-chan** 2021-03-25 20:38 UTC
Labels: canarie
